"use strict"

module.exports = {
  url: "http://celine.tech",
  title: "Web Dev Bit by Bit",
  tagline: "Always Be Coding",
  copyright: "© Built by Céline Cholé",
  author: {
    name: "Céline Cholé",
    bio: "Full Stack Web Instructor",
    contacts: {
      linkedin: "https://www.linkedin.com/in/celinechole/",
      github: "https://github.com/CelineChole",
      portfolio: "https://celinechole.com/",
      freecodecamp: "",
      twitter: "",
    },
  },
  labels: [
    {
      tag: "react",
      tech: "React",
      name: "DiReact",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "nodejs",
      tech: "Node.js",
      name: "DiNodejsSmall",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "DiGitMerge",
      size: 20,
      color: "white",
    },
    {
      tag: "javascript",
      tech: "JavaScript",
      name: "DiJsBadge",
      size: 20,
      color: "yellow",
    },
    {
      tag: "css",
      tech: "CSS",
      name: "DiCss3Full",
      size: 20,
      color: "teal",
    },
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "firebase",
      tech: "Firebase",
      name: "DiFirebase",
      size: 20,
      color: "orange",
    },
    {
      tag: "angular",
      tech: "Angular",
      name: "DiAngularSimple",
      size: 20,
      color: "red",
    },
    {
      tag: "html",
      tech: "HTML",
      name: "FaHtml5",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "mongodb",
      tech: "MongoDB",
      name: "DiMongodb",
      size: 20,
      color: "green",
    },
    {
      tag: "vscode",
      tech: "VS Code",
      name: "DiVisualstudio",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "github",
      tech: "GitHub",
      name: "DiGithubBadge",
      size: 20,
      color: "white",
    },
    {
      tag: "bootstrap",
      tech: "Bootstrap",
      name: "DiBootstrap",
      size: 20,
      color: "purple",
    },
    {
      tag: "links",
      tech: "Links",
      name: "FiLink",
      size: 20,
      color: "white",
    },
    {
      tag: "terminal",
      tech: "Terminal",
      name: "DiTerminal",
      size: 20,
      color: "white",
    },
  ],
}
